dataset: oakink2_maniptrans

model:
  backbone_name: dinov2
  hidden_dim: 1024
  action_dim: 132        # 44 keypoints × 3 coords = 132 (matches EgoDex format)
  depth: 32
  num_heads: 16
  mlp_ratio: 2.0
  do_compile: False

data:
  rh_pkl_path: /mnt/data/tim_data/dexwm/data/oakink2_processed/retargeted_artimano/mano2artimano_rh/scene_01__A001%2B%2Bseq__083f7a577484ba7929a9__2023-04-27-19-25-24@0.pkl
  lh_pkl_path: /mnt/data/tim_data/dexwm/data/oakink2_processed/retargeted_artimano/mano2artimano_lh/scene_01__A001%2B%2Bseq__083f7a577484ba7929a9__2023-04-27-19-25-24@0.pkl
  rgb_dir: /mnt/data/tim_data/dexwm/data/oakink2_processed/rgb
  max_context_len: 60
  num_context: 8
  img_size: 224
  aug: True
  var_time: True

train:
  global_seed: 0
  batch_size: 1
  num_workers: 2
  epochs: 50000
  optim:
    lr: 1e-4
    lr_decoder: 1e-5
    weight_decay: 1e-5
  scheduler:
    final_div_factor: 1e3
    max_lr: 1e-4
    decoder_final_div_factor: 1e3
    decoder_max_lr: 1e-5
  do_eval: False
  eval_freq: 50
  kp_weight: 0            # no keypoint supervision
  resume: /mnt/data/tim_data/dexwm/data/checkpoints/egodex_0.pth_24000.tar
  save_name: oakink2_artimano_multistep_ft_new_map

wandb:
  do_wandb: True
  project: dexwm
  entity: kttu_tim-uc-san-diego
  name: oakink2_maniptrans_multistep_ft_artimano
  api_key: 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
