dataset: robocasa_random
model:
  backbone_name: dinov2 # dinov2, dinov3_large, vjepa2_vitg_256, siglip2_so400m_patch14_384, webssl_vitl
  hidden_dim: 1024
  action_dim: 132
  depth: 32
  num_heads: 16
  mlp_ratio: 2.0
  do_compile: True
data:
  root_folder: /media/david/9b7b2bdd-e9f1-4cba-ad1e-9e8b477c0305/tim_data/dexwm/data
  max_context_len: 80
  num_context: 8
  img_size: 224
  aug: False
  full_seq: True
train:
  global_seed: 0
  batch_size: 8
  num_workers: 4  # reduced from 12 for single-GPU desktop
  epochs: 20
  optim:
    lr: 1e-3
    lr_decoder: 1e-4
    weight_decay: 1e-5
  scheduler:
    final_div_factor: 1
    max_lr: 1e-5
    decoder_final_div_factor: 1e3
    decoder_max_lr: 1e-4
  do_eval: True
  eval_freq: 100
  kp_weight: 100
  resume: /media/david/9b7b2bdd-e9f1-4cba-ad1e-9e8b477c0305/tim_data/dexwm/data/checkpoints/egodex_0.pth_24000.tar
  save_name: robocasa_random_multistep
wandb:
  do_wandb: False
  project: dexwm
  entity: dexwm
  name: robocasa_random_multistep
